### ISSUE TITLE
Question? Not really an issue but question.

### ISSUE THREAD

**Issue by taihuy** [jenschristianschroder/CDS-Batch-Operations-via-Web-API#1]
Hei,

Thanks very much for your contribution. 
I have a question about what is your axes really mean? Does the y-axis mean number of requests that have been sent to the CDS?

**Comment by jenschristianschroder** [comment]
Sorry it took so long to answer.

Number of requests are the number of operations send.
Batch is the duration via batch operation
Single is duration when sending operations one by one
